// Generated by scripts/gen-tokens.mjs from yantrik-os crates/yantrik-ui-kit/slint/app_color.slint.
// Do not edit: change the OS, then regenerate.

/** `AppColor.hue-for-app(id)`: which of the palette's hues an app wears. Unknown ids wear none. */
export const APP_HUES: Readonly<Record<string, string>> = {
  "notes": "amber",
  "editor": "violet",
  "documents": "blue",
  "spreadsheet": "green",
  "presentation": "orange",
  "snippets": "magenta",
  "email": "blue",
  "calendar": "red",
  "notifications": "orange",
  "music": "pink",
  "media": "pink",
  "image": "magenta",
  "studio": "violet",
  "blender": "orange",
  "arcade": "orange",
  "files": "sky",
  "terminal": "green",
  "system": "azure",
  "sysmonitor": "lime",
  "network": "azure",
  "containers": "teal",
  "packages": "teal",
  "devices": "slate",
  "downloads": "teal",
  "browser": "teal",
  "weather": "azure",
  "memory": "violet",
  "agents": "violet",
  "recipes": "yellow",
  "bond": "pink",
  "personality": "magenta",
  "skills": "lime",
  "permissions": "red",
  "settings": "slate",
  "about": "slate",
  "launchpad": "blue",
};

/** `AppColor.on-tile(hue)`: the light hues carry the dark ink glyph; the rest a white one. */
export const INK_HUES: ReadonlySet<string> = new Set(["lime","yellow","amber"]);
