// The site's design tokens, generated from the OS's own theme, so the website cannot drift from the
// desktop it shows. Reads yantrik-os/crates/yantrik-design-tokens/slint/theme.slint, resolves every
// `out property` of the Theme and AccentPreset globals to its DARK value (the accent at the default
// teal preset), and writes src/os/tokens.css as `--y-<name>` custom properties.
//
// Fails (non-zero) if a token the site uses has gone from the OS: REQUIRED below.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

const osRepo = resolve(process.env.YANTRIK_OS ?? "../yantrik-os");
const themePath = resolve(osRepo, "crates/yantrik-design-tokens/slint/theme.slint");
const out = new URL("../src/os/tokens.css", import.meta.url);
const src = readFileSync(themePath, "utf8").replace(/\/\/[^\n]*/g, "");

// Every `out property <type> name: expr;` in a global block, by global name.
function globals(text) {
  const found = {};
  const re = /export\s+global\s+(\w+)\s*\{/g;
  let m;
  while ((m = re.exec(text))) {
    let depth = 0, i = re.lastIndex - 1, start = i;
    for (; i < text.length; i++) {
      if (text[i] === "{") depth++;
      else if (text[i] === "}" && --depth === 0) break;
    }
    const body = text.slice(start + 1, i);
    const props = {};
    const pre = /(?:in-)?out\s+property\s*<\s*(\w+)\s*>\s+([\w-]+)\s*:\s*([^;]+);/g;
    let p;
    while ((p = pre.exec(body))) props[p[2]] = { type: p[1], expr: p[3].replace(/\s+/g, " ").trim() };
    found[m[1]] = props;
  }
  return found;
}

const all = globals(src);
const theme = all.Theme ?? {};
const accent = all.AccentPreset ?? {};

function darkOf(expr, scope, seen = new Set()) {
  // A conditional on dark mode: the first branch is the dark value.
  const dark = expr.match(/ThemeMode\.dark\s*\?\s*(#[0-9a-fA-F]{3,8}|[\d.]+(?:px|ms)?)/);
  if (dark) return dark[1];
  // Accent presets: index 0 (teal), dark.
  const preset = expr.match(/index\s*==\s*0\s*\?\s*\(\s*ThemeMode\.dark\s*\?\s*(#[0-9a-fA-F]{3,8})/);
  if (preset) return preset[1];
  const ref = expr.match(/^(?:root|Theme|AccentPreset)\.([\w-]+)$/);
  if (ref) {
    const name = ref[1];
    if (seen.has(name)) return null;
    seen.add(name);
    const target = expr.startsWith("AccentPreset") ? accent[name] : scope[name] ?? accent[name];
    return target ? darkOf(target.expr, scope, seen) : null;
  }
  const plain = expr.match(/^(#[0-9a-fA-F]{3,8}|-?[\d.]+(?:px|ms|%)?|true|false)$/);
  return plain ? plain[1] : null;
}

const vars = [];
const unresolved = [];
for (const [name, { type, expr }] of Object.entries({ ...accent, ...theme })) {
  if (!["color", "length", "duration", "int", "float"].includes(type)) continue;
  const v = darkOf(expr, theme);
  if (v == null) unresolved.push(name);
  else vars.push([name, type === "int" || type === "float" ? v.replace(/px$/, "") : v]);
}

const REQUIRED = [
  "bg-deep", "bg-surface", "bg-card", "bg-elevated", "text-primary", "text-secondary", "text-dim",
  "accent", "accent-light", "accent-dim", "amber", "color-danger", "color-success", "color-warning",
  "border-subtle", "fs-hero", "fs-body", "fs-caption", "fs-micro", "fs-mono", "sp-4", "r-lg", "dur-normal",
];
const have = new Set(vars.map(([n]) => n));
const missing = REQUIRED.filter((n) => !have.has(n));
if (missing.length) {
  console.error(`tokens: the OS theme no longer has ${missing.join(", ")} (or they did not resolve)`);
  process.exit(1);
}

const css =
  `/* Generated by scripts/gen-tokens.mjs from yantrik-os ${themePath.split(/[\\/]/).slice(-4).join("/")}.\n` +
  `   Dark values; accent at the default teal preset. Do not edit: change the OS, then regenerate. */\n` +
  `:root {\n` +
  vars.map(([n, v]) => `  --y-${n}: ${v};`).join("\n") +
  `\n}\n`;
mkdirSync(dirname(out.pathname.replace(/^\/([A-Za-z]:)/, "$1")), { recursive: true });
writeFileSync(out, css);
console.log(`tokens: ${vars.length} written${unresolved.length ? `, ${unresolved.length} not resolvable (computed in Slint): ${unresolved.slice(0, 8).join(", ")}${unresolved.length > 8 ? ", …" : ""}` : ""}`);
