// The OS's stroke icons, generated from the OS's own icon set so the replica cannot draw a glyph
// the desktop does not. Reads yantrik-os/crates/yantrik-ui-kit/slint/icon.slint and writes
// src/os/icons.ts:
//
//   ICONS        every `out property <string> name: "<svg path>"` of the Icons global
//   APP_GLYPHS   the `Icons.app(id)` table: shell app id → icon name
//
// How they are drawn is src/os/Icon.tsx, which follows the Slint Icon component: a 20×20 viewbox
// fitted into the icon's box less its stroke, a 1.6px stroke by default, no fill, and Slint's
// default line cap and join (butt and miter).
//
// Fails (non-zero) if an icon the replica uses has gone from the OS: REQUIRED below.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const osRepo = resolve(process.env.YANTRIK_OS ?? "../yantrik-os");
const iconPath = resolve(osRepo, "crates/yantrik-ui-kit/slint/icon.slint");
const out = new URL("../src/os/icons.ts", import.meta.url);
const src = readFileSync(iconPath, "utf8");

// The body of `export global Icons { … }`, comments removed (a path never contains `//`).
const start = src.indexOf("export global Icons");
if (start < 0) {
  console.error("icons: icon.slint has no `export global Icons`");
  process.exit(1);
}
let depth = 0;
let i = src.indexOf("{", start);
const open = i;
for (; i < src.length; i++) {
  if (src[i] === "{") depth++;
  else if (src[i] === "}" && --depth === 0) break;
}
const body = src.slice(open + 1, i).replace(/\/\/[^\n]*/g, "");

const icons = {};
const prop = /out\s+property\s*<\s*string\s*>\s+([\w-]+)\s*:\s*"([^"]*)"\s*;/g;
let m;
while ((m = prop.exec(body))) icons[m[1]] = m[2];

// `public pure function app(id: string) -> string { return id == "x" ? self.y : … : ""; }`
const appFn = body.match(/function\s+app\s*\(\s*id\s*:\s*string\s*\)[^{]*\{([\s\S]*?)\n\s*\}/);
const appGlyphs = {};
if (appFn) {
  const arm = /id\s*==\s*"([^"]+)"\s*\?\s*(?:self|root)\.([\w-]+)/g;
  while ((m = arm.exec(appFn[1]))) appGlyphs[m[1]] = m[2];
}

const REQUIRED = [
  "apps", "power", "network", "wifi", "shield", "eye", "companion", "window", "browser", "notes",
  "close", "minus", "win-maximize", "win-restore", "chevron-right", "chevron-left", "chevron-down",
  "check", "warning", "clock", "template", "refresh", "import", "plus", "list", "search", "star",
  "export", "trash", "arrow-left", "arrow-right", "folder", "more", "lock", "cloud", "hybrid",
];
const missing = REQUIRED.filter((n) => !(n in icons));
const badGlyph = Object.entries(appGlyphs).filter(([, n]) => !(n in icons));
if (missing.length || !appFn || badGlyph.length) {
  if (missing.length) console.error(`icons: the OS icon set no longer has ${missing.join(", ")}`);
  if (!appFn) console.error("icons: icon.slint has no `Icons.app(id)` function to read");
  if (badGlyph.length) console.error(`icons: Icons.app names glyphs that are not in the set: ${badGlyph.map(([a, n]) => `${a}→${n}`).join(", ")}`);
  process.exit(1);
}

const q = (s) => JSON.stringify(s);
const ts =
  `// Generated by scripts/gen-icons.mjs from yantrik-os crates/yantrik-ui-kit/slint/icon.slint.\n` +
  `// Do not edit: change the OS, then regenerate.\n\n` +
  `/** Every stroke icon of the OS's Icons global: SVG path commands on a 20×20 grid. */\n` +
  `export const ICONS = {\n` +
  Object.entries(icons).map(([n, d]) => `  ${q(n)}: ${q(d)},`).join("\n") +
  `\n} as const;\n\n` +
  `export type IconName = keyof typeof ICONS;\n\n` +
  `/** \`Icons.app(id)\`: a shell app id to its glyph. Ids it does not name have none. */\n` +
  `export const APP_GLYPHS: Readonly<Record<string, IconName>> = {\n` +
  Object.entries(appGlyphs).map(([id, n]) => `  ${q(id)}: ${q(n)},`).join("\n") +
  `\n};\n\n` +
  `/** \`Icons.app-or-window(id)\`: the app's glyph, or a plain window for an app the set does not know. */\n` +
  `export function appOrWindow(id: string): string {\n` +
  `  const name = APP_GLYPHS[id];\n` +
  `  return name ? ICONS[name] : ICONS.window;\n` +
  `}\n`;

writeFileSync(out, ts);
console.log(`icons: ${Object.keys(icons).length} icons, ${Object.keys(appGlyphs).length} app glyphs`);
